replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "savkusamdetka23/kbot"
  tag: "v1.1.4-aa71300"
  os: linux
  arch: amd64
secret:
  name: kbot
  env: TELE_TOKEN
  key: token
securityContext:
  privileged: true
