# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "savkusamdetka23/kbot"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.3-24bfe38"
  os: ""
  arch: ""
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  value: "6762316228:AAGiiWtqo8RNSv6CA2hRfX1eby6016XiXbc"
securityContext:
  privileged: true
